language: python
python:
  - "3.4"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install markdown2 lxml
# command to run tests, e.g. python setup.py test
script:  python -m unittest discover
